version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:stretch
    working_directory: ~/tmp/workspace
    steps:
      
      # install dependencies for client
      - checkout
      - restore_cache:
          keys:
            - npm-client-dependencies-{{ checksum "client/package-lock.json" }}
            - npm-dependencies-
      - run: cd client && npm install
      - save_cache:
          paths:
            - ./client/node_modules/
          key: npm-client-dependencies-{{ checksum "client/package-lock.json" }}    
   
      # install dependencies for server
      - restore_cache:
          keys:
            - npm-server-dependencies-{{ checksum "server/package-lock.json" }}
            - npm-dependencies-
      - run: cd server && npm install
      - save_cache:
          paths:
            - ./server/node_modules/
          key: npm-server-dependencies-{{ checksum "server/package-lock.json" }}

   # build the dev for testing
      - run: cd client && npm run build-prod
      - run: cd server && npm run tsc
      - persist_to_workspace:
          root: .
          paths:
            - client/dist/*
            - client/package.json
            - server/dist/*
            - server/package.json

  test:
    docker:
    - image: circleci/node:stretch
    working_directory: ~/tmp/workspace
    steps:
      - attach_workspace:
          at: /home/circleci/tmp/workspace/
      - run: cd server && npm install
      - run: cd server && npm test
 # build-prod:
 # publish:
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
