version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:stretch
    working_directory: ~/tmp/workspace
    steps:
   # install dependencies for client and server
      - checkout
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package-lock.json" }}
            - npm-dependencies-
      - run: cd client && npm install
      - run: cd server && npm install
      - save_cache:
          paths:
            - ~/client/node_modules
            - ~/server/node_modules
          key: npm-dependencies-{{ checksum "package-lock.json" }}
   # build the dev
      - run: cd client && npm run build-prod
      - run: cd server && npm run tsc
      - persist_to_workspace:
          root: .
          paths:
            - client/*
            - server/*
      - run: ls server
 #  - restore_cache:
 #     keys:
 #      - v1-dependencies-{{ checksum "package.json" }}
 #      # fallback to using the latest cache if no exact match is found
 #      - v1-dependencies-
  test:
    docker:
    - image: circleci/node:stretch
    working_directory: ~/tmp/workspace
    steps:
      - attach_workspace:
          at: /home/circleci/tmp/workspace/
      - run: cd server && npm test
 # build-prod:
 # publish:
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
